# Generated by Django 5.2.6 on 2025-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('palabras_clave', models.CharField(max_length=300)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
