# Generated by Django 5.2.6 on 2025-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='Imagen (URL)')),
                ('palabras_clave', models.CharField(help_text='Separar con comas', max_length=250)),
            ],
        ),
    ]
